jobs:
  dispatch-release-desktop:
    name: Setup Release Desktop
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
    - name: Collect Workflow Telemetry
      uses: Nfsaavedra/workflow-telemetry-action@raw_data
      with:
        save_raw_stats: true
    - if: ${{ github.event_name == 'push' }}
      name: dispatch desktop release by tag
      uses: benc-uk/workflow-dispatch@v1
      with:
        inputs: '{ "build-type": "canary", "is-draft": false, "is-pre-release": true
          }'
        workflow: release-desktop.yml
    - if: ${{ github.event_name == 'schedule' }}
      name: dispatch desktop release by schedule
      uses: benc-uk/workflow-dispatch@v1
      with:
        inputs: '{ "build-type": "canary", "is-draft": false, "is-pre-release": true
          }'
        ref: canary
        workflow: release-desktop.yml
name: Release Desktop Automatically
'on':
- workflow_dispatch
permissions: write-all
